INSERT INTO assets (type, name)
VALUES
    ('SURGICAL_INSTRUMENT', 'SCALPEL'),
    ('SURGICAL_INSTRUMENT', 'SCISSORS'),
    ('SURGICAL_INSTRUMENT', 'FORCEPS'),
    ('SURGICAL_INSTRUMENT', 'CLAMPS'),
    ('MACHINE', 'MONITOR'),
    ('MACHINE', 'ANESTESIA MACHINE'),
    ('EQUIPMENT', 'TABLE'),
    ('EQUIPMENT', 'OPERATIONAL LIGHT'),
    ('EQUIPMENT', 'ELECTROSURGICAL UNIT'),
    ('OTHER_ESSENTIAL_TOOL', 'THERMOMETER'),
    ('OTHER_ESSENTIAL_TOOL', 'HYPODERMIC NEEDLE'),
    ('MACHINE', 'STERILIZER'),
    ('OTHER_ESSENTIAL_TOOL', 'PULSE OXIMETRY');
