services:
  db:
    image: postgres:latest
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "opteamer", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_DB: opteamer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - op

  opteamer-backend:
    image: "tzetzaka2/opteamer:s1"
    container_name: opteamer-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/opteamer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - op

  opteamer-frontend:
    build:
      context: ../opteamer-client
      dockerfile: Dockerfile
    container_name: opteamer-frontend
    ports:
      - "4200:80"
    depends_on:
      - opteamer-backend
    networks:
      - op


networks:
  op:
    driver: "bridge"

