services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: opteamer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  opteamer-app:
    build:
      context: ..  # Set to the root of your project
      dockerfile: docker/Dockerfile  # Path to the Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/opteamer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    volumes:
      - ./target:/app
    command: ["./wait-for-it.sh", "db", "--", "java", "-jar", "/app/opteamer.jar"]
